### ISSUE TITLE
Wrong decode on a HEIF with transparency 

### ISSUE THREAD

**Issue by imfantuan** [david-poirier-csn/pyheif#20]
Hello, could you please check this file, THX.
[tree-with-transparency.heif.zip](https://github.com/david-poirier-csn/pyheif/files/4619703/tree-with-transparency.heif.zip)

**Comment by david-poirier-csn** [comment]
An interesting issue! It turned out to be caused by the image width not being a multiple of 4, not the transparency. I've added a `stride` property to the `HeifFile` class to enable proper loading of oddly-sized images into Pillow, like so:

```
from PIL import Image
import pyheif

heif_file = pyheif.read("IMG_7424.HEIC")
image = Image.frombytes(
    heif_file.mode, 
    heif_file.size, 
    heif_file.data,
    "raw",
    heif_file.mode,
    heif_file.stride,
    )

```

I'll release a new version to pypi shortly with this update. Thanks!
